<a href="https://colab.research.google.com/github/yucordova/Secret-number-game/blob/main/Proyecto_direcciones_IP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importaciones y base de datos**

In [ ]:
#Importaciones
import pandas as pd

# Cargar el dataset
file_path = '/content/drive/MyDrive/Colab Notebooks/Copia de dbip-city-lite-2024-09.csv.gz'
base_de_datos = pd.read_csv(file_path)

# Ver las primeras filas del dataset
print(base_de_datos.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/Copia de dbip-city-lite-2024-09.csv.gz'

# **Creación de DataFrame**

In [ ]:
#CREAR DATAFRAME
df = pd.DataFrame(base_de_datos)
df

NameError: name 'pd' is not defined

In [ ]:
#Número de columnas y filas
df.shape

NameError: name 'df' is not defined

In [ ]:
#tipo de datos
df.dtypes

0.0.0.0           object
0.255.255.255     object
ZZ                object
ZZ.1              object
Unnamed: 4        object
Unnamed: 5        object
0                float64
0.1              float64
dtype: object

# **Modificación de las columnas**

In [ ]:
#Renombrar columnas
column_name_mapping={
    '0.0.0.0':'primera_direccion_ip',
    '0.255.255.255':'ultima_direccion_ip',
    'ZZ':'codigo_continente',
    'ZZ.1':'nombre_continente',
    'Unnamed: 4':'codigo_iso_3166.alpha2',
    'Unnamed: 5':'Pais_pertenencia_UE',
    '0':'latitud',
    '0.1':'longitud'
}

df_renamed=df.rename(columns=column_name_mapping)
df_renamed

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,1.0.0.0,1.0.0.255,OC,AU,Queensland,South Brisbane,-27.4767,153.01700
1,1.0.1.0,1.0.3.255,AS,CN,Fujian,Wenquan,26.0998,119.29700
2,1.0.4.0,1.0.7.255,OC,AU,Victoria,Narre Warren,-38.0267,145.30100
3,1.0.8.0,1.0.15.255,AS,CN,Guangdong,Guangzhou,23.1317,113.26600
4,1.0.16.0,1.0.16.255,AS,JP,Tokyo,Chiyoda,35.6916,139.76800
...,...,...,...,...,...,...,...,...
6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891460,fc00::,fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,NaN,NaN,0.0000,0.00000
6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891462,fe80::,febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,NaN,NaN,0.0000,0.00000
6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595

In [ ]:
#Asignación de variables
dfr=df_renamed

# **Contando e indentificando NaNs**

In [ ]:
#DETECTAR VALORES NA
dfr.isna()

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
6891459,False,False,False,False,False,False,False,False
6891460,False,False,False,False,True,True,False,False
6891461,False,False,False,False,False,False,False,False
6891462,False,False,False,False,True,True,False,False
6891463,False,False,False,False,False,False,False,False

In [ ]:
#Conteo de valores NaNs por columna
dfr.isna().sum()

primera_direccion_ip            0
ultima_direccion_ip             0
codigo_continente         3219361
nombre_continente             539
codigo_iso_3166.alpha2      17497
Pais_pertenencia_UE           153
latitud                         0
longitud                        0
dtype: int64

In [ ]:
# Contar NaNs en cada columna
nan_por_columna = dfr.isna().sum()
print(f"NaNs por columna:\n{nan_por_columna}\n")

print("-"*20)

# Contar NaNs en cada fila
nan_por_fila = dfr.isna().sum(axis=1)
print(f"NaNs por fila:\n{nan_por_fila}")

NaNs por columna:
primera_direccion_ip            0
ultima_direccion_ip             0
codigo_continente         3219361
nombre_continente             539
codigo_iso_3166.alpha2      17497
Pais_pertenencia_UE           153
latitud                         0
longitud                        0
dtype: int64

--------------------
NaNs por fila:
0          0
1          0
2          0
3          0
4          0
          ..
6891459    0
6891460    2
6891461    0
6891462    2
6891463    0
Length: 6891464, dtype: int64

# **Limpieza de NaNs**

In [ ]:
# Crear una copia del DataFrame para manipulaciones seguras
df_clean = dfr.copy()
df_clean.head()

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,1.0.0.0,1.0.0.255,OC,AU,Queensland,South Brisbane,-27.4767,153.017
1,1.0.1.0,1.0.3.255,AS,CN,Fujian,Wenquan,26.0998,119.297
2,1.0.4.0,1.0.7.255,OC,AU,Victoria,Narre Warren,-38.0267,145.301
3,1.0.8.0,1.0.15.255,AS,CN,Guangdong,Guangzhou,23.1317,113.266
4,1.0.16.0,1.0.16.255,AS,JP,Tokyo,Chiyoda,35.6916,139.768

In [ ]:
# Eliminar filas donde cualquier valor es NaN
df_clean.dropna(axis=0, how='any')

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,1.0.0.0,1.0.0.255,OC,AU,Queensland,South Brisbane,-27.4767,153.01700
1,1.0.1.0,1.0.3.255,AS,CN,Fujian,Wenquan,26.0998,119.29700
2,1.0.4.0,1.0.7.255,OC,AU,Victoria,Narre Warren,-38.0267,145.30100
3,1.0.8.0,1.0.15.255,AS,CN,Guangdong,Guangzhou,23.1317,113.26600
4,1.0.16.0,1.0.16.255,AS,JP,Tokyo,Chiyoda,35.6916,139.76800
...,...,...,...,...,...,...,...,...
6891457,2c10::,2dff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891458,2e00::,3fff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,DE,Hesse,Frankfurt am Main,50.1109,8.68213
6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595

In [ ]:
# Eliminar columnas donde cualquier valor es NaN
df_clean.dropna(axis=1, how='all')

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,1.0.0.0,1.0.0.255,OC,AU,Queensland,South Brisbane,-27.4767,153.01700
1,1.0.1.0,1.0.3.255,AS,CN,Fujian,Wenquan,26.0998,119.29700
2,1.0.4.0,1.0.7.255,OC,AU,Victoria,Narre Warren,-38.0267,145.30100
3,1.0.8.0,1.0.15.255,AS,CN,Guangdong,Guangzhou,23.1317,113.26600
4,1.0.16.0,1.0.16.255,AS,JP,Tokyo,Chiyoda,35.6916,139.76800
...,...,...,...,...,...,...,...,...
6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891460,fc00::,fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,NaN,NaN,0.0000,0.00000
6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891462,fe80::,febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,NaN,NaN,0.0000,0.00000
6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595

In [ ]:
#Fill de los NaNs
df_final=df_clean.fillna(
    {
        'codigo_continente': 'Desconocido',
        'nombre_continente': 'Desconocido',
        'codigo_iso_3166.alpha2': 'Desconocido',
        'Pais_pertenencia_UE': 'Desconocido'
    }
)
df_final

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
0,1.0.0.0,1.0.0.255,OC,AU,Queensland,South Brisbane,-27.4767,153.01700
1,1.0.1.0,1.0.3.255,AS,CN,Fujian,Wenquan,26.0998,119.29700
2,1.0.4.0,1.0.7.255,OC,AU,Victoria,Narre Warren,-38.0267,145.30100
3,1.0.8.0,1.0.15.255,AS,CN,Guangdong,Guangzhou,23.1317,113.26600
4,1.0.16.0,1.0.16.255,AS,JP,Tokyo,Chiyoda,35.6916,139.76800
...,...,...,...,...,...,...,...,...
6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891460,fc00::,fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.0000,0.00000
6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891462,fe80::,febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.0000,0.00000
6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595

# **Comprobación de NaNs**

In [ ]:
#Conteo de NaNs por columna
df_final.isna().sum()

primera_direccion_ip      0
ultima_direccion_ip       0
codigo_continente         0
nombre_continente         0
codigo_iso_3166.alpha2    0
Pais_pertenencia_UE       0
latitud                   0
longitud                  0
dtype: int64

In [ ]:
# Contar NaNs en cada columna
nan_por_columna = df_final.isna().sum()
print(f"NaNs por columna:\n{nan_por_columna}\n")

print("-"*20)

# Contar NaNs en cada fila
nan_por_fila = df_final.isna().sum(axis=1)
print(f"NaNs por fila:\n{nan_por_fila}")

NaNs por columna:
primera_direccion_ip      0
ultima_direccion_ip       0
codigo_continente         0
nombre_continente         0
codigo_iso_3166.alpha2    0
Pais_pertenencia_UE       0
latitud                   0
longitud                  0
dtype: int64

--------------------
NaNs por fila:
0          0
1          0
2          0
3          0
4          0
          ..
6891459    0
6891460    0
6891461    0
6891462    0
6891463    0
Length: 6891464, dtype: int64

# **Reindexar**

In [ ]:
#Reidexación
df_final.reset_index().tail()

,index,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
6891459,6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891460,6891460,fc00::,fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.0000,0.00000
6891461,6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595
6891462,6891462,fe80::,febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.0000,0.00000
6891463,6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.9219,7.16595

# **Obtención de métricas**

# **Conteo de países**

In [ ]:
# Suponiendo que la columna de país se llama 'País' o similar
# Paso 1: Encuentra los países únicos
unique_countries = df_final['nombre_continente'].unique()
print("nombre_continente", unique_countries)

nombre_continente ['AU' 'CN' 'JP' 'TH' 'IN' 'MY' 'KR' 'SG' 'US' 'DE' 'HK' 'TW' 'VN' 'CA'
 'KH' 'PH' 'NL' 'BR' 'AR' 'PS' 'ES' 'FR' 'GB' 'CZ' 'IT' 'CH' 'AT' 'GR'
 'RU' 'SE' 'IL' 'AE' 'IE' 'CO' 'DK' 'PT' 'GH' 'ZA' 'CM' 'PE' 'TR' 'FI'
 'PL' 'JO' 'BE' 'RO' 'KE' 'UG' 'AM' 'TZ' 'BI' 'CL' 'NO' 'LU' 'BG' 'UA'
 'EG' 'QA' 'IQ' 'VA' 'LV' 'RS' 'IS' 'OM' 'IR' 'GE' 'SK' 'KZ' 'LT' 'EE'
 'HR' 'SA' 'MT' 'HU' 'CY' 'NZ' 'BH' 'ID' 'MX' 'VU' 'PG' 'CR' 'SY' 'LB'
 'SC' 'CW' 'AX' 'ZM' 'CD' 'SI' 'MD' 'MK' 'LI' 'JE' 'MA' 'BA' 'AZ' 'BY'
 'KG' 'RE' 'MV' 'GG' 'IM' 'GI' 'LY' 'YE' 'UZ' 'YT' 'MQ' 'GP' 'MF' 'GF'
 'SN' 'SZ' 'MC' 'AL' 'DZ' 'KW' 'DO' 'BW' 'XK' 'PM' 'LA' 'GU' 'BT' 'AQ'
 'NG' 'EC' 'VE' 'PA' 'ZZ' 'PR' 'BO' 'VI' 'MN' 'TV' 'TL' 'WS' 'LK' 'CC'
 'BD' 'PK' 'SB' 'FJ' 'CK' 'TO' 'NP' 'MO' 'NI' 'JM' 'TT' 'SS' 'AF' 'VG'
 'GD' 'KN' 'AG' 'BL' 'PY' 'VC' 'LC' 'BS' 'DM' 'KY' 'MM' 'UY' 'ME' 'TN'
 'BB' 'GT' 'TM' 'TK' 'NC' 'WF' 'AD' 'GL' 'TJ' 'FO' 'SV' 'HN' 'CV' 'PF'
 'GN' 'BN' 'ML' 'MZ' 'CI' 'ZW' 'LR' 'MU' 'MG' 'AO' 'Desconocido' 'SD' 'MW'
 'BJ' 'RW' 'CG' 'GM' 'LS' 'BF' 'SO' 'SL' 'GA' 'NE' 'CF' 'TG' 'GQ' 'AS'
 'MR' 'DJ' 'TD' 'SH' 'NR' 'FM' 'SR' 'AW' 'BM' 'SM' 'BZ' 'MH' 'ET' 'NU'
 'PW' 'KI' 'KP' 'CU' 'HT' 'GY' 'ST' 'KM' 'ER' 'GW' 'FK' 'AI' 'MP' 'TC'
 'SX' 'MS' 'BQ' 'GS' 'IO' 'PN' 'UM' 'NF' 'CX' 'SJ' 'HM' 'TF' 'BV' 'EH']

In [ ]:

# Paso 2: Contar el número de registros por país
country_counts = df_final['nombre_continente'].value_counts()
print("Número de registros por país:n", country_counts)

df_final.tail(250)

Número de registros por país:n nombre_continente
US    2934150
FR     424472
BR     402544
GB     330445
DE     303766
       ...
SJ          9
TF          6
HM          4
BV          4
EH          3
Name: count, Length: 251, dtype: int64

,primera_direccion_ip,ultima_direccion_ip,codigo_continente,nombre_continente,codigo_iso_3166.alpha2,Pais_pertenencia_UE,latitud,longitud
6891214,2c0f:fe38:2101::,2c0f:fe38:2104:ffff:ffff:ffff:ffff:ffff,AF,KE,Mombasa County,Mombasa,-4.04348,39.66820
6891215,2c0f:fe38:2105::,2c0f:fe38:2105:ffff:ffff:ffff:ffff:ffff,AF,KE,Marsabit County,Moyale,3.52661,39.05610
6891216,2c0f:fe38:2106::,2c0f:fe38:2106:ffff:ffff:ffff:ffff:ffff,AF,KE,Kiambu County,Kiambu,-1.17139,36.83560
6891217,2c0f:fe38:2107::,2c0f:fe38:211f:ffff:ffff:ffff:ffff:ffff,AF,KE,Mombasa County,Mombasa,-4.04348,39.66820
6891218,2c0f:fe38:2120::,2c0f:fe38:217f:ffff:ffff:ffff:ffff:ffff,AF,KE,Nairobi County,Nairobi,-1.26391,36.75860
...,...,...,...,...,...,...,...,...
6891459,4000::,fbff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.92190,7.16595
6891460,fc00::,fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.00000,0.00000
6891461,fe00::,fe7f:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.92190,7.16595
6891462,fe80::,febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff,ZZ,ZZ,Desconocido,Desconocido,0.00000,0.00000
6891463,fec0::,ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,EU,CH,Fribourg,Murten/Morat,46.92190,7.16595

In [ ]:
# Usar value_counts() para obtener la frecuencia de todos los países
conteo_paises = df_final['nombre_continente'].value_counts()
conteo_paises.head(60)

nombre_continente
US    2934150
FR     424472
BR     402544
GB     330445
DE     303766
CA     204508
JP     174783
AU     164127
KR     135458
IT     122649
NL     119003
ES     105572
IN      94323
CN      88973
PL      81985
RU      68974
VN      61787
MX      56121
CH      47217
TR      45492
SE      39360
PT      35132
AR      33769
LR      32001
EG      30430
AT      28159
BE      26887
MA      25483
IR      23988
DK      22955
CO      22731
TW      22134
ZA      21693
TN      21590
NO      21344
SA      20324
CZ      19577
HK      19222
ID      18151
RO      17928
SG      16150
CL      15299
UA      15297
FI      15051
HU      14641
GR      14243
PH      14026
IE      13916
UY      11569
PK      11173
VE      10897
IL      10742
TH      10618
KE      10445
DZ      10411
BG       9608
SK       9420
KZ       9313
AE       9204
BD       8933
Name: count, dtype: int64

In [ ]:
#Visualización del conteo de los países por rango
conteo_paises.iloc[61:119]

nombre_continente
MY    8595
SI    8544
NZ    6660
HR    6638
EC    6335
RS    5412
CR    5126
DO    5102
LT    4829
BY    3705
LU    3603
MU    3556
JO    3201
EE    3187
BO    3178
LV    3070
CI    3043
IQ    2821
BH    2770
KW    2690
PA    2602
GE    2510
ZM    2468
NG    2287
CY    2282
PY    2244
QA    2222
SY    2041
MD    1960
NP    1935
OM    1888
IS    1833
PR    1693
BA    1586
MK    1539
PS    1464
UG    1434
GT    1432
SN    1419
LB    1385
LK    1382
ZW    1274
AL    1207
KH    1197
AZ    1171
SV    1163
AO    1156
AM    1096
HN    1007
TZ     982
MT     974
UZ     967
MM     910
GH     899
YE     767
MZ     694
JM     650
SC     614
Name: count, dtype: int64